#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend wadza.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        167154-web-01 35.175.128.220
        167154-web-02 34.204.61.159
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
