#!/usr/bin/env bash
# script to display "Best School" 9 times and after 9th iteration display "Hi"

i=1

while [ $i -le 10 ] 
do
      echo "Best School"
      if [ $i -eq 9 ]
      then
	  echo "Hi"
      fi
      ((i++))
done
