#!/usr/bin/env bash
# Script that displays content of current directory in list format.
#   Only displays the part of the name after the first dash.

mylist=$(ls)
for i in $mylist; do
  echo "$i" | cut -d '-' -f2
done
